######################################################################
#
# File name : fpga2_simulate.do
# Created on: Sat Nov 14 17:01:34 -0300 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -debugDB -fsmdebug -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.fpga2 xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {fpga2_wave.do}

view wave
view structure
view signals

do {fpga2.udo}

run 1000ns
