######################################################################
#
# File name : fpga2_compile.do
# Created on: Sat Nov 14 17:01:29 -0300 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech64_2019.4\\win64\\vlib modelsim_lib/work
C:\\modeltech64_2019.4\\win64\\vlib modelsim_lib/msim

C:\\modeltech64_2019.4\\win64\\vlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_2019.4\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_2019.4\\win64\\vlog  -incr -work xil_defaultlib  \
"../../../../verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/lib/axis/rtl/arbiter.v" \
"../../../../verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/arp.v" \
"../../../../verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/arp_cache.v" \
"../../../../verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/arp_eth_rx.v" \
"../../../../verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/arp_eth_tx.v" \
"../../../../verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/lib/axis/rtl/axis_async_fifo.v" \
"../../../../verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/lib/axis/rtl/axis_async_fifo_adapter.v" \
"../../../../verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/lib/axis/rtl/axis_fifo.v" \
"../../../../verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/axis_gmii_rx.v" \
"../../../../verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/axis_gmii_tx.v" \
"../../../../verilog_ethernet_acq7.srcs/sources_1/imports/fpga/rtl/debounce_switch.v" \
"../../../../verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/eth_arb_mux.v" \
"../../../../verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/eth_axis_rx.v" \
"../../../../verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/eth_axis_tx.v" \
"../../../../verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/eth_mac_1g.v" \
"../../../../verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/eth_mac_1g_rgmii.v" \
"../../../../verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/eth_mac_1g_rgmii_fifo.v" \
"../../../../verilog_ethernet_acq7.srcs/sources_1/new/fpga_core_4.v" \
"../../../../verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/iddr.v" \
"../../../../verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/ip.v" \
"../../../../verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/ip_arb_mux.v" \
"../../../../verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/ip_complete.v" \
"../../../../verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/ip_eth_rx.v" \
"../../../../verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/ip_eth_tx.v" \
"../../../../verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/lfsr.v" \
"../../../../verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/oddr.v" \
"../../../../verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/lib/axis/rtl/priority_encoder.v" \
"../../../../verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/rgmii_phy_if.v" \
"../../../../verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/ssio_ddr_in.v" \
"../../../../verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/lib/axis/rtl/sync_reset.v" \
"../../../../verilog_ethernet_acq7.srcs/sources_1/imports/fpga/rtl/sync_signal.v" \
"../../../../verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/udp.v" \
"../../../../verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/udp_checksum_gen.v" \
"../../../../verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/udp_complete.v" \
"../../../../verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/udp_ip_rx.v" \
"../../../../verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/udp_ip_tx.v" \

C:\\modeltech64_2019.4\\win64\\vcom  -2008 -work xil_defaultlib  \
"../../../../verilog_ethernet_acq7.srcs/sources_1/imports/sources_1/imports/sources_1/imports/Nexys3_AD2_DA1_Source/TWICtl.vhd" \
"../../../../verilog_ethernet_acq7.srcs/sources_1/new/i2cmaster4.vhd" \
"../../../../verilog_ethernet_acq7.srcs/sources_1/imports/sources_1/imports/sources_1/imports/Nexys3_AD2_DA1_Source/pmodAD2_ctrl.vhd" \

C:\\modeltech64_2019.4\\win64\\vcom  -2008 -work xil_defaultlib  \
"../../../../verilog_ethernet_acq7.srcs/sources_1/imports/sources_1/imports/sources_1/new/fifo_comp_axi_s.vhd" \
"../../../../verilog_ethernet_acq7.srcs/sources_1/new/timestamp_cnt3.vhd" \

C:\\modeltech64_2019.4\\win64\\vlog  -incr -work xil_defaultlib  \
"../../../../verilog_ethernet_acq7.srcs/sources_1/new/fpga2.v" \

# compile glbl module
C:\\modeltech64_2019.4\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

