######################################################################
#
# File name : fpga2_wave.do
# Created on: Sat Nov 14 15:17:50 -0300 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
