# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.runs/synth_1/fpga2.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param simulator.modelsimInstallPath C:/modeltech64_2019.4/win64
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.cache/wt [current_project]
set_property parent.project_path C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/lib/axis/rtl/arbiter.v
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/arp.v
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/arp_cache.v
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/arp_eth_rx.v
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/arp_eth_tx.v
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/lib/axis/rtl/axis_async_fifo.v
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/lib/axis/rtl/axis_async_fifo_adapter.v
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/lib/axis/rtl/axis_fifo.v
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/axis_gmii_rx.v
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/axis_gmii_tx.v
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/imports/fpga/rtl/debounce_switch.v
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/eth_arb_mux.v
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/eth_axis_rx.v
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/eth_axis_tx.v
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/eth_mac_1g.v
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/eth_mac_1g_rgmii.v
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/eth_mac_1g_rgmii_fifo.v
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/new/fpga_core_4.v
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/iddr.v
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/ip.v
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/ip_arb_mux.v
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/ip_complete.v
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/ip_eth_rx.v
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/ip_eth_tx.v
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/lfsr.v
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/oddr.v
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/lib/axis/rtl/priority_encoder.v
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/rgmii_phy_if.v
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/ssio_ddr_in.v
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/lib/axis/rtl/sync_reset.v
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/imports/fpga/rtl/sync_signal.v
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/udp.v
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/udp_checksum_gen.v
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/udp_complete.v
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/udp_ip_rx.v
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/imports/fpga/lib/eth/rtl/udp_ip_tx.v
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/new/fpga2.v
}
read_vhdl -library xil_defaultlib {
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/imports/sources_1/imports/sources_1/imports/Nexys3_AD2_DA1_Source/TWICtl.vhd
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/new/i2cmaster4.vhd
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/imports/sources_1/imports/sources_1/imports/Nexys3_AD2_DA1_Source/pmodAD2_ctrl.vhd
}
read_vhdl -vhdl2008 -library xil_defaultlib {
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/imports/sources_1/imports/sources_1/new/fifo_comp_axi_s.vhd
  C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/sources_1/new/timestamp_cnt3.vhd
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/constrs_1/imports/fpga/fpga.xdc
set_property used_in_implementation false [get_files C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/constrs_1/imports/fpga/fpga.xdc]

read_xdc C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/constrs_1/imports/fpga/eth.xdc
set_property used_in_implementation false [get_files C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/constrs_1/imports/fpga/eth.xdc]

read_xdc -unmanaged C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/constrs_1/imports/fpga/lib/eth/syn/rgmii_phy_if.tcl
set_property used_in_implementation false [get_files C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/constrs_1/imports/fpga/lib/eth/syn/rgmii_phy_if.tcl]

read_xdc -unmanaged C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/constrs_1/imports/fpga/lib/eth/syn/eth_mac_1g_rgmii.tcl
set_property used_in_implementation false [get_files C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/constrs_1/imports/fpga/lib/eth/syn/eth_mac_1g_rgmii.tcl]

read_xdc -unmanaged C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/constrs_1/imports/fpga/lib/eth/syn/eth_mac_fifo.tcl
set_property used_in_implementation false [get_files C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/constrs_1/imports/fpga/lib/eth/syn/eth_mac_fifo.tcl]

read_xdc -unmanaged C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/constrs_1/imports/fpga/lib/eth/lib/axis/syn/axis_async_fifo.tcl
set_property used_in_implementation false [get_files C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/constrs_1/imports/fpga/lib/eth/lib/axis/syn/axis_async_fifo.tcl]

read_xdc -unmanaged C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/constrs_1/imports/fpga/lib/eth/lib/axis/syn/sync_reset.tcl
set_property used_in_implementation false [get_files C:/src/verilog_ethernet_acq7/verilog_ethernet_acq7.srcs/constrs_1/imports/fpga/lib/eth/lib/axis/syn/sync_reset.tcl]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top fpga2 -part xc7a200tsbg484-1
OPTRACE "synth_design" END { }


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fpga2.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file fpga2_utilization_synth.rpt -pb fpga2_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
